### ISSUE TITLE
MT validation blocks missing

### ISSUE THREAD

**Issue by neptunes5thmoon** [janelia-cosem/heinrich-2021a#2]

**Comment by d-v-b** [comment]
on it!

**Comment by neptunes5thmoon** [comment]
I think we still need input from @nilsec on the format

**Comment by neptunes5thmoon** [comment]
fixed https://github.com/janelia-cosem/heinrich-2021a/commit/dff2e07aeb1bfca32c5ae95eda48dc7f86bab8a5
