### ISSUE TITLE
downloading data

### ISSUE THREAD

**Issue by xiuliren** [janelia-cosem/heinrich-2021a#3]
Hi, thanks for the sharing of data.

I just tried to download the data following the documentation in README.md, but got an error.

```
aws s3 cp s3://janelia-cosem-publications/heinrich-2021a/ ./ --recursive
fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Comment by d-v-b** [comment]
hi @jingpengw 
try `aws s3 cp s3://janelia-cosem-publications/heinrich-2021a/ ./ --recursive --no-sign-request`

**Comment by xiuliren** [comment]
thank you! this command works!

Best,
Jingpeng
